firstproject/firstproject/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('main/', include('main.urls'))
]

firstproject/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('record/', views.create_blogpost, name='record'),
    path('show/',views.show_students, name='show'),
    path('show_results/', views.show_results, name='show_results'),
    path('registration/', views.registration, name='registration'),
    path('new_group/', views.group_registration, name='group_registration'),
]

firstproject/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class BlogPost(models.Model):
    title = models.CharField(max_length = 150)
    body = models.TextField()
    timestamp = models.DateTimeField()
    
# class User(models.Model):
#     name = models.CharField(max_length = 20)
#     surname = models.CharField(max_length = 25)
#     login = models.CharField(max_length = 20, unique = True)

#     class Meta:
#         abstract = True

class Group(models.Model):
    number = models.IntegerField(unique = True)

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)

firstproject/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from main.models import BlogPost, Student, Group
from django.template import Context
from django.utils import timezone
from django.contrib.auth.models import User


def create_blogpost(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        body = request.POST.get('body')
        timestamp = request.POST.get('timestamp')

        # Convert the timestamp string to a datetime object
        timestamp = timezone.datetime.strptime(timestamp, '%Y-%m-%dT%H:%M')

        # Create a new BlogPost instance
        new_blogpost = BlogPost(title=title, body=body, timestamp=timestamp)

        # Save the instance to the database
        new_blogpost.save()

    # Render the form template for GET requests
    return render(request, 'main/record.html')
def show_blogpost(request):
    all_objects = BlogPost.objects.all()
    return render(request, 'main/show.html', {'all_objects': all_objects})

def show_results(request):
    query = request.GET.get('query', '')
    filtered_objects = Student.objects.all().filter(user__username__icontains=query)
    return render(request, 'main/show.html', {'all_objects' : filtered_objects})

def index(request):
    posts = BlogPost.objects.all()
    return render(request, 'main/index.html', {'post' : posts})
    # return HttpResponse("<h4>Main Page</h4>")

def registration(request):
    if request.method == 'POST':
        name = request.POST.get('first_name')
        surname = request.POST.get('last_name')
        login = request.POST.get('username')
        group_num = request.POST.get('group')
        password = request.POST.get('password')
        group = Group.objects.get(number=group_num)
        user = User.objects.create(first_name=name, last_name=surname, username=login, password=password)
        new_student = Student(user=user, group_id=group.id)
        new_student.save()
    return render(request, 'main/registration.html')

def show_students(request):
    all_objects = Student.objects.all()
    return render(request, 'main/show.html', {'all_objects': all_objects})

def group_registration(request):
    if request.method == 'POST':
        number = request.POST.get('group_number')
        new_group = Group(number=number)
        new_group.save()
    return render(request, 'main/new_group.html')

firstproject/main/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% for post in posts %}
    <title>{{post.title}}</title>
    {% endfor %}
</head>
<body>
    {% for post in posts %}
    <p>{{post.content}}</p>
    {% endfor %}
</body>
</html>

firstproject/main/templates/main/new_group.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Blog Post</title>
    {% load static %}
    <link rel="stylesheet" href="{% static './css/registration.css' %}">
</head>
<body>


<h2>Create New Group</h2>

<form method="post" action="{% url 'group_registration' %}">
    {% csrf_token %}

    <label for="group">number</label>
    <input type="text" id="id_group" name="group_number" required>

    <button type="submit">Create New Group</button>
</form>

</body>
</html>

firstproject/main/templates/main/record.html
<!-- myapp/templates/create_blogpost.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Blog Post</title>
</head>
<body>

<h2>Create Blog Post</h2>

<form method="post" action="{% url 'record' %}">
    {% csrf_token %}

    <label for="id_title">Title:</label>
    <input type="text" id="id_title" name="title" required>

    <br>

    <label for="id_body">Body:</label>
    <textarea id="id_body" name="body" rows="4" cols="50" required></textarea>

    <br>

    <label for="id_timestamp">Timestamp:</label>
    <input type="datetime-local" id="id_timestamp" name="timestamp" required>

    <br>

    <button type="submit">Create Blog Post</button>
</form>

</body>
</html>

firstproject/main/templates/main/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Blog Post</title>
    {% load static %}
    <link rel="stylesheet" href="{% static './css/registration.css' %}">
</head>
<body>

<h2>Registration page</h2>

<form method="post" action="{% url 'registration' %}">
    {% csrf_token %}

    <label for="first_name">name</label>
    <input type="text" id="id_first_name" name="first_name" required>

    <br>

    <label for="last_name">surname</label>
    <input type="text" id="id_last_name" name="last_name" required>

    <br>

    <label for="username">username</label>
    <input type="text" id="id_username" name="username" required>

    <br>

    <label for="password">password</label>
    <input type="text" id="id_password" name="password" required>

    <br>
    <label for="group">group</label>
    <input type="text" id="id_group" name="group" required>

    <br>
    <button type="submit">Create New User</button>
</form>

</body>
</html>

firstproject/main/templates/main/show.html
<!-- myapp/templates/create_blogpost.html -->

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Show Blog Posts</title>
        {% load static %}
        <link rel="stylesheet" href="{% static './css/styles.css' %}">
    </head>
<body>

<h2>Книги русских писателей</h2>
<div class="search-container">
    <h2>Поиск по имени</h2>
    <form action="{% url 'show_results' %}" method="get">
        <input id="search-input" type="text" name="query" placeholder="Впишите название книги">
        <button type="submit">Поиск</button>
    </form>
</div>
<div class="blog-container">

    <!-- {% for object in all_objects %}
        <div class="blog-card">
            <h3 class="blog-title">{{ object.title }}</h3>
            <p class="blog-body">{{ object.body }}</p>
            <p class="blog-timestamp">Опубликовано: {{ object.timestamp }}</p>
        </div>
    {% endfor %} -->


    {% for object in all_objects %}
        <div class="blog-card">
            <h3 class="blog-title">{{ object.user.username}}</h3>
            <p class="blog-body">{{ object.user.first_name}} {{ object.user.last_name }}</p>
            <p class="blog-timestamp">Группа №: {{ object.group.number }}</p>
        </div>
    {% endfor %}
</div>

</body>
</html>